### ISSUE TITLE
Implement RandomForest Classifier for Model Training and Prediction

### ISSUE THREAD

**Issue by Mubashir-Ul-Hassan** [Mubashir-Ul-Hassan/data-science-projects#30]
I would like to contribute by implementing a RandomForest Classifier to enhance the model's performance in predicting outcomes. The proposed solution uses n_estimators=100 and sets a fixed random_state=10 for reproducibility.

Task Breakdown:
Implement the RandomForest classifier.
Train the model using x_train and y_train.
Make predictions on the test set x_test.
Evaluate model accuracy with y_test using accuracy_score.

**Comment by VadisettyRahul** [comment]
I'm interested @Mubashir-Ul-Hassan  please assign to me.

**Comment by Mubashir-Ul-Hassan** [comment]
@VadisettyRahul assign to you.
