### ISSUE TITLE
Implement Linear Regression Model for Axis Bank Price Prediction

### ISSUE THREAD

**Issue by Mubashir-Ul-Hassan** [Mubashir-Ul-Hassan/data-science-projects#37]
This task involves implementing a **Linear Regression** model to predict Axis Bank stock prices. The aim is to build and train the model, make predictions, and evaluate the model's performance using metrics like **accuracy score** and **confusion matrix**.

**Task Requirements:**

- Implement Linear Regression for predicting Axis Bank stock prices.
- Train the model using the provided x_train and y_train.
- Make predictions on the x_test data.
- Evaluate the model's performance using suitable metrics (though confusion_matrix and accuracy_score are shown, feel free to adjust based on regression tasks).
- Ensure the implementation is clean and well-documented.

**Guidelines:**

- Use Python and scikit-learn for the model.
- Follow clean code principles.
- Provide comments for key sections.
- Submit your code via a Pull Request with appropriate documentation.

**Comment by VadisettyRahul** [comment]
@Mubashir-Ul-Hassan assign to me.
