### ISSUE TITLE
Implement K-Nearest Neighbors (KNN) for Iris Flower Classification

### ISSUE THREAD

**Issue by Mubashir-Ul-Hassan** [Mubashir-Ul-Hassan/data-science-projects#40]
This issue involves implementing the K-Nearest Neighbors (KNN) algorithm for the Iris Flower Classification task. The goal is to classify different species of iris flowers based on their features, such as petal length and width. The KNN model should be built with n_neighbors=3.

Task Details:

- Implement the KNeighborsClassifier from scikit-learn.
- Train the model using the provided Iris dataset (can be accessed via sklearn.datasets).
- Set n_neighbors=3 for the classifier.
- Test the model and report accuracy.

Contributor Requirements:

- Ensure the code is well-documented.
- Add appropriate test cases to validate the model.
- The solution should return the accuracy of the KNN model on the test dataset.

**Comment by VadisettyRahul** [comment]
@Mubashir-Ul-Hassan please assign to me.
