### ISSUE TITLE
Implement K-Nearest Neighbors and RandomForest Classifier for Heart Disease Classification

### ISSUE THREAD

**Issue by Mubashir-Ul-Hassan** [Mubashir-Ul-Hassan/data-science-projects#47]
We are looking for contributors to implement both K-Nearest Neighbors (KNN) and RandomForest Classifier for heart disease classification. The goal is to compare the performance of these models and enhance our existing classification pipeline.

**K-Nearest Neighbors (KNN):**

- Implement the KNeighborsClassifier from sklearn.neighbors.
- Train and evaluate the model using the heart disease dataset.
- RandomForest Classifier:
- Implement the RandomForestClassifier from sklearn.ensemble.
- Set n_estimators=15 for the model.
- Train and evaluate the RandomForest model as well.

**Expected Outcomes:**

- Contributors should train both models (KNN and RandomForest) and report the performance metrics (e.g., accuracy, precision, recall) for each classifier.
- Provide detailed documentation on how to run the models, including necessary preprocessing steps and dataset information.

**Comment by VadisettyRahul** [comment]
@Mubashir-Ul-Hassan please assign to me.
