### ISSUE TITLE
Implement K-Nearest Neighbors (KNN) Classifier for Telecom Customer Churn Prediction

### ISSUE THREAD

**Issue by Mubashir-Ul-Hassan** [Mubashir-Ul-Hassan/data-science-projects#48]
We are looking for contributors to implement a K-Nearest Neighbors (KNN) Classifier to predict Telecom Customer Churn. The proposed solution involves using 5 neighbors (n_neighbors=5) for classification.

**The task involves:**

- Training the KNN model using the provided telecom churn dataset.
- Evaluating the model based on accuracy or other relevant metrics.
- Documenting the process and findings.

**Contribution Instructions:**

- Use the Telecom Customer Churn dataset (you can request for it if unavailable).
- Implement and tune the KNN model for optimal performance.
- Submit a pull request with the implemented code, a brief description of the approach, and the results obtained.

**Comment by VadisettyRahul** [comment]
@Mubashir-Ul-Hassan assign to me.
